MDScreen:
    name: "IntroScreen"
    MDFloatLayout:
        md_bg_color: "black"
        Image:
            source: 'lion.png'
            size_hint: None, None
            size: 900, 900
            pos_hint: {"center_x": 0.5, "center_y": 0.6}
        Label:
            id: typings
            text: ""
            color: "gold"
            font_size: 45
            bold: True
            pos_hint: {"center_x": 0.5, "center_y": 0.25}


        