MDScreen:
    name: "IntroScreen"
    MDFloatLayout:
        md_bg_color: "black"
        Image:
            source: 'lion.png'
            size: 1200, 1200
            pos_hint: {"center_x": 0.5, "center_y": 0.55}
        Label:
            id: typings
            text: ""
            color: "gold"
            font_size: 45
            bold: True
            pos_hint: {"center_x": 0.5, "center_y": 0.25}


        
